name: Update docs

on:
    release:
        types:
            - published
        workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-python@v5
                with:
                    python-version: 3.x

            -   uses: actions/cache@v4
                with:
                    key:  ${{ github.ref }}
                    path: .cache

            -   run: pip install mkdocs-material mkdocs-minify-plugin pillow cairosvg
            -   run: mkdocs gh-deploy --force
        env:
            SOCIAL_CARDS: true # Enable social cards building
            SITE_URL:     https://placeholders.pb4.eu # Set the site url for mkdocs
